apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-gateway
  template:
    metadata:
      labels:
        app: msvc-gateway
    spec:
      containers:
      - image: eloynh/gateway:latest
        name: gateway
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
  namespace: default
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: msvc-gateway
  type: LoadBalancer