apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: database
        volumeMounts:
          -  name: data-mysql
             mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: postgres-pvc
#          hostPath:
#            path: /var/lib/postgresql/data
#            type: DirectoryOrCreate