apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
  namespace: default
type: Opaque
data:
  username: cm9vdA== #root
  password: c2FzYQ== #sasa
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
  namespace: default
type: Opaque
data:
  username: cG9zdGdyZXM= #postgres
  password: c2FzYQ== #sasa