apiVersion: v1
kind: Service
metadata:
  name: msvc-usuarios
  namespace: default
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: msvc-usuarios
  type: LoadBalancer
