apiVersion: v1
kind: Service
metadata:
  name: postgres14
  namespace: default
spec:
  ports:
  - port: 5432 #puerto para acceder desde el exterior
    protocol: TCP
    targetPort: 5432 #puerto interno
  selector:
    app: postgres14
  type: ClusterIP
