apiVersion: v1
kind: Service
metadata:
  name: msvc-cursos
  namespace: default
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: msvc-cursos
  type: LoadBalancer
