apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
  namespace: default
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: msvc-auth
  type: LoadBalancer